lexi/urls.py
from django.urls import path

from .import views

app_name = 'lexi'
urlpatterns = [
    #ToDo: Define Generic Views (https://docs.djangoproject.com/en/2.2/intro/tutorial04/)
    path('', views.index, name='index'),
    path('analysis/', views.analysis, name='analysis'),
    path('word_test/', views.word_test, name='word test'),
    #path('import', views.import_words, name='import words'),   #For admin purposes only! ToDo: Move to Admin module.
]

lexiProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('lexi.urls')),
    path('admin/', admin.site.urls),
]

lexi/models.py
from django.db import models

# Create your models here.
class Configuration(models.Model):
    THESAURUS = 'TH' 
    DATABASE = 'DB'
    AI_MODEL = 'AI'
    SOURCE_CHOICES = [
        (THESAURUS, 'Thesaurus'),
        (DATABASE, 'Database'),
        (AI_MODEL, 'AI Model'),
    ]
    source = models.CharField(
        max_length = 2,
        choices = SOURCE_CHOICES,
        default = THESAURUS
    )
    threshold = models.FloatField(default = 0.8) # Look if these is the best way of creating configuration variables. It will be only one record of the Configuration Model.
    subset_common_words = models.IntegerField(null=False)

    def __str__(self):
        return ('Source: ' + self.source + ' - Threshold: ' + str(self.threshold*100)) + '% - Common Words subset: ' + str(self.subset_common_words)

    def get_source_description(self, code):
        for source in self.SOURCE_CHOICES:
            if code == source[0]:
                return source[1]

class Word(models.Model):
    word = models.CharField(primary_key=True, max_length=50)
    is_common = models.BooleanField(default=False)
    is_business_word = models.BooleanField(default=False)
    creation_datetime = models.DateTimeField(auto_now_add=True)
    creation_user = models.CharField(max_length=20, default='admin')   # ToDo: Change using the session user request.session['member_id']
    suggestions = models.ManyToManyField(to='self')
    # ToDo: Add index to know which are the first n most common words. The index could come with the bulk load.

    def __str__(self):
        return self.word

    # ToDo: Check and create properly encapsulation.
    

lexi/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import html

# Import Lexi functions
from .business_rules import make_analysis, import_common_words, validate_word

# Create your views here.
global_variables = {
    'url': 'http://www.thesaurus.com/browse/',
    'suggestions': '',
    'count': 0,
    'commonWordsPercentage': 0.0,
    'uncommonWordsPercentage': 0.0
}

def index(request):
    return render(request, 'lexi/index.html')

def analysis(request):
    post = request.POST.copy()
    input_test = post['inputText']
    if(input_test != ""):
        checked_message = make_analysis(input_test, global_variables)
        return render(request, 'lexi/analysis.html', {
            'checked_message': checked_message,
            'global_variables': global_variables
        })
    else:
        print("There is not a text to analyze")
        return render(request, 'lexi/index.html', {
            "error_message": "There is not a text to analyze."
        })

def word_test(request):
    result = {}
    word = ''
    if request.POST.dict():
        post = request.POST.copy()
        word = post['word']
        if word:
            result = validate_word(word, global_variables)
    return render(request, 'lexi/word_test.html', {
        'word': word,
        'result': result,
    })

def import_words(request):
    import_common_words()
    return render(request, 'lexi/index.html', {})

#ToDo: Use generic views (https://docs.djangoproject.com/en/2.2/intro/tutorial04/)

lexi/templates/lexi/analysis.html
{% extends 'lexi/base.html' %}
{% block content %}
<div class="container">
    <div class="row py-3">
        <div class="col">
            <h1 class="center-aligned">Results</h1>
        </div>
    </div>
    <div class="row py-3">
        <div class="col-md justify-content-end" style="margin: auto; display: inline-flex;">
            <div style="margin-right: 1rem;">Common Words</div>
            <div class="bg-success progress-bar-striped common-icon"></div>
        </div>
        <div class="col-md" style="margin: auto; display: inline-flex;">
            <div class="bg-danger progress-bar-striped common-icon"></div>
            <div style="margin-left: 1rem;">Uncommon Words</div>
        </div>
    </div>
    <div class="row py-3">
        <div class="col-md justify-content-end progress-labels text-success">
            {{global_variables.commonWordsPercentage|floatformat:"2"}}%
        </div>
        <div class="col-md-7">
            <div class="progress">
                <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: {{global_variables.commonWordsPercentage}}%" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: {{global_variables.uncommonWordsPercentage}}%" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div class="col-md progress-labels text-danger">
            {{global_variables.uncommonWordsPercentage|floatformat:"2"}}%
        </div>
    </div>
    <div class="row py-3">
        <div class="col">
            <h1 class="center-aligned {{global_variables.result_class}}">{{global_variables.result}}</h1>
        </div>
    </div>
    <div class="row py-3">
        <div class="col-md-9">
            <div class="col-md">
                <h2>Text result</h2>
                <p class="lead" id="checkedMessage">{{ checked_message|safe }}</p>
            </div>
            <div class="col-md">
                <p><strong>Notes</strong></p>
                <p>This analysis was made based on the {{global_variables.subset_common_words}} most common words and the defined threshold for the evaluation ({{global_variables.threshold}}%). The suggestions source was {{global_variables.source}}.</p>
                <p>Elapsed time: {{global_variables.elapsed_time}}</p>
            </div>
        </div>
        <div class="col-md">
            {{ global_variables.suggestions|safe }}
        </div>
    </div>
</div>
{% endblock %}

lexi/templates/lexi/base.html
<link href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% load static  %}
<link rel="stylesheet" href="{% static 'lexi/style.css' %}">
<div>
    <div class="card-header p-0">
        <nav class="navbar navbar-expand-lg navbar-light bg-light py-0 px-5">
            <a class="navbar-brand" id="lexi-title" href="{% url 'lexi:index' %}">Lexi</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!--div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Log in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Sign up</a>
                    </li>
                </ul>
            </div-->
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    <div class="card-footer text-muted">
        <a href="{% url 'lexi:index' %}">Home</a> | <a href="{% url 'lexi:word test' %}">Test a word</a>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'lexi/lexi.js' %}"></script>

lexi/templates/lexi/detail.html
<div class="container">
        <div class="row">
            <div class="col">
                <h1>Lexi</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md section">
                <div class="col section-title">
                    <h2>Text to validate</h2>
                </div>
                <div class="w-100"></div>
                <div class="col section-description">
                    <p class="lead" id="originalMessage">{{ analysis.input_text }}</p>
                    <div class="col">
                        <button type="submit" class="btn" disabled="disabled">1k</button>
                        <button type="button" class="btn" disabled="disabled">2k</button>
                        <button type="button" class="btn" disabled="disabled">5k</button>
                        <button type="button" class="btn" disabled="disabled">10k</button>
                        <button type="button" class="btn" disabled="disabled">20k</button>
                        <button type="button" class="btn" disabled="disabled">Cenitex</button>
                    </div>
                </div>
            </div>
            <div class="col-md section">
                <div class="col section-title">
                <h2>Results</h2>
                </div>
                <div class="w-100"></div>
                <div class="col section-description">
                    <p class="lead" id="commonWords"></p>
                    <p class="lead" id="cenitexWords"></p>
                    <p class="lead" id="notCommonWords"></p>
                    <p class="lead" id="words"></p>
                    <p class="lead" id="message"></p>
                    <p class="lead" id="percentage"></p>
                </div>
            </div>
            <div class="w-100"></div>
            <div class="col-md section">
                <div class="col section-title">
                    <h2>Text result</h2>
                </div>
                <div class="w-100"></div>
                <div class="col section-description">
                    <p class="lead" id="checkedMessage"></p>
                </div>
            </div>
            <div class="col-md section">
                <div class="col section-title">
                    <h2>Chart</h2>
                </div>
                <div class="w-100"></div>
                <div class="col section-description">
                    <textarea class="form-control" name="input" id="textToCheck" rows="8"></textarea>
                </div>
            </div>
        </div>
    </div>

lexi/templates/lexi/index.html
{% extends 'lexi/base.html' %}
{% block content %}
<div class="container">
    <div class="row py-3">
        <div class="col-md">
            <p>After analyzing one of the three problem statements we prioritized, we came up with Lexi to help Cenitex to improve its capacity to communicate messages to customers in a language that is accessible. Lexi does this by using the most common words in English.</p>
            <p>Lexi is a system (web app), developed with Python as Programming Language and Django as web framework, that will help Cenitex validate how accessible is the message of most of their comms before sending them to customers. What Lexi does is getting a text, analyze it, and validate each word to determine whether that word is either common or uncommon, based on the group of common words configured.</p>
            <p>Then, Lexi presents the same text but it highlights each uncommon word with an underline. Moreover, Lexi also indicates how accessible the whole input text is by showing also, as a result, a percentage. A ‘’Passed!” message will be shown if that percentage is higher or equal to the one defined in Lexi’s configuration. Otherwise, the message “Check the message” will appear, asking the user for double-checking the message.</p>
        </div>
        <div class="col-md justify-content-center">
                <img class="rounded mx-auto d-block" src="https://dummyimage.com/550x400/705798/fff" alt=""> <!--ToDo: Change image!-->
        </div>
    </div>
    <div class="row py-2">
        <div class="col-md">
            <h2>Instructions to follow</h2>
            <ol>
                <li>Give a Lexi a text to analyze in the following textarea.</li>
                <li>Click on one of the two buttons to tell Lexi to evaluate your text.</li>
                <li>Sit confortable and wait till Lexi does its work and show you the results.</li>
                <li>See the result and the percentages of both common and uncommon words. Based on that, make any change you need to do in order to get an acceptable threshold.</li>
            </ol>
            {% if error_message%}
            <div class="alert alert-danger" role="alert">{{ error_message }}</div>
            {% endif %}
        </div>
        <div class="w-100"></div>
        <div class="col-md">
            <form action="{% url 'lexi:analysis' %}" method="post">
            {%csrf_token%}
                <div>
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>  <!--ToDo: Loading icon-->
                    <button type="submit" class="btn btn-outline">Validate accessibility</button>
                </div>
                <textarea class="form-control my-4" name="inputText" id="textToCheck" rows="8">{{ original_message }}</textarea>
            <!--
    Please be advised that disruptions are expected to affect peak-hour traffic and public transport tonight, with a climate change protest planned in the CBD.

    Protestors are expected to meet at the State Library on Swanston Street at 5pm, before separating to a series of locations in the CBD to block foot and road traffic. The protest is expected to finish at 7pm.

    Victoria Police are aware of the protest and are calling on people to be patient, plan their journey, and allow extra time for their commute where possible.

    Please speak to your manager if you think you may be impacted by the protest.-->
            </form>
        </div>
    </div>
</div>
{% endblock %}

lexi/templates/lexi/word_test.html
{% extends 'lexi/base.html' %}
{% block content %}
<div class="container">
    <div class="row py-3">
        <div class="col">
            <h1 class="center-aligned">Test any word</h1>
        </div>
    </div>
    <div class="row py-3">
        <form action="{% url 'lexi:word test' %}" method="post" class="form-inline" style="margin: 0 auto;">
            {% csrf_token %}
            <div class="col">
                <input type="text" name="word" placeholder="Type a word" class="form-control" value="{{ word }}">
            </div>
            <div class="col">
                <button type="submit" class="btn btn-primary">Validate</button>
            </div>
        </form>
    </div>
    <div class="row py-3">
        <div class="col">
            <h2 class="center-aligned {{ result.result_class }}">{{ result.result }}</h2>
        </div>
    </div>
</div>
{% endblock content %}